# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_PASSWORD=moodlepassword
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - /opt/moodle/mariadb:/var/lib/mysql  # Persistencia de la base de datos
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpassword
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - /opt/moodle/moodle:/bitnami/moodle        # Archivos de Moodle
      - /opt/moodle/moodledata:/bitnami/moodledata # Datos subidos por usuarios (ej: cursos)
    depends_on:
      - mariadb

